# If you have OpenSSL installed, we recommend updating
# the following line to use "https"
source 'http://rubygems.org'

gem "middleman", "~> 3.3.2"
gem "font-awesome-middleman", path: "../../../font-awesome-middleman"
